### ISSUE TITLE
When I test on the LFWA dataset,the output of model is a sequence of one and zero.So how could I match the 1 and 0 to the real face attribute? 

### ISSUE THREAD

**Issue by explorer66** [Li-Wanhua/Label2Label#1]

**Comment by Li-Wanhua** [comment]
Hi, thanks for your interest.
1 denotes a positive attribute and 0 means the person has no such attribute. 
For the meaning of an attribute, please refer to the label file of the LFWA dataset. We follow the exact order defined in the LFWA dataset. Or you can see table 16 in our paper, which is also consistent with the order in the LFWA dataset.
