### ISSUE TITLE
link to data file train_lfwa.txt and val_lfwa.txt are invalid

### ISSUE THREAD

**Issue by awsong** [Li-Wanhua/Label2Label#4]
<img width="814" alt="image" src="https://github.com/Li-Wanhua/Label2Label/assets/787544/53194ec4-ff00-43ee-a0be-8c3cbf07bd4c">

**Comment by Li-Wanhua** [comment]
Hi,

Thanks for your interest in our work. We now have updated the link.
For train_lfwa.txt: https://pan.baidu.com/share/init?surl=ze2Vi48VY-fmSWiPKlBsaQ&pwd=hegy
For val_lfwa.txt: https://pan.baidu.com/s/14Dr_E1BjuEzTq-8DwwFQtg?pwd=33w8

Hope it can help you.
